spring:
  datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/musicms?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai# ??????
  username: root
  password: zk123456
mybatis:
  type-aliases-package: com.zk.domain
  mapper-locations: classpath:/mappers/*Mapper.xml